import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import Header from "@/components/header";
import Footer from "@/components/footer";


// import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: 'JaoRium | 情報戦に、終止符を。',
  description: 'JaoRiumは、受験生が無料で先輩の一次情報にアクセスできるオンラインメンタリングサービス。環境に左右されず、誰もが本物の情報で未来を選べる社会を目指します。',
  openGraph: {
    title: 'JaoRium',
    description: '情報戦に、終止符を。',
    url: 'https://sampleblog-iota.vercel.app',
    siteName: 'JaoRium',
    // images: [
    //   {
    //     url: 'https://example.com/og-image.png', // 公開URLを指定
    //     width: 1200,
    //     height: 630,
    //   },
    // ],
    locale: 'ja_JP',
    type: 'website',
  },
  // twitter: {
  //   card: 'summary_large_image',
  //   title: 'サービス名',
  //   description: 'Twitter用説明文',
  //   images: ['https://example.com/og-image.png'],
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <speedInsights /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Header propClassName="bg-white shadow-md relative z-0" />
        {children}
        
        <Footer />
      </body>
    </html>
  );
}
